/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static org.testng.Assert.*;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class AppTest {
    WebDriver driver;

    @BeforeClass
    public void setUp() {
        // Set up the WebDriverManager before running the tests
        driver=WebDriverManager.getDriver();
    }

    @Test 
    public void testCase01() throws InterruptedException {
        // Test case 1: Open the website and check the title
        try {
            System.out.println("Running test case 1");

            driver.get("https://www.google.com/");
            WebElement searchBox = driver.findElement(By.xpath("//textarea[@class='gLFyf']"));
            searchBox.sendKeys("OpenAI");
            searchBox.sendKeys(Keys.ENTER);

            WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
            WebElement firstResult = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//h3[contains(text(),'') and contains(@class,'LC20lb MBeuO DKV0Md')]")));
            assertTrue(firstResult.getText().contains("OpenAI"), "The first result does not contain 'OpenAI'");

            if(firstResult.getText().contains("OpenAI")) {
                ScreenshotUtil screenshotUtil = new ScreenshotUtil(driver);
                screenshotUtil.takeScreenshot();
                System.out.println("Test case 1 passed: The first result contains 'OpenAI'");
            } else {
                ScreenshotUtil screenshotUtil = new ScreenshotUtil(driver);
                screenshotUtil.takeScreenshot();
                System.out.println("Test case 1 failed: The first result does not contain 'OpenAI'");
            }
        } catch (Exception e) {
            // TODO: handle exception
            System.out.println("An error occurred in test case 1: " + e.getMessage());
        }
    }

    @AfterClass
    public void tearDown() {
        // Quit the WebDriver after all tests are done
        WebDriverManager.quitDriver();
    }
}
